services:
  goilerplate_app:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - "8008:8008"
    environment:
      - DB_HOST=goilerplate_mysql
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - STATIC_PATH=web/dist
    depends_on:
      goilerplate_mysql:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - .:/app

  goilerplate_mysql:
    image: mysql:8.0
    container_name: ${COMPOSE_MYSQL_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - mysql_data:/var/lib/mysql # Persistent storage for MySQL data

networks:
  app-network:
    driver: bridge
volumes:
  mysql_data:
    driver: local
